export const CHANGE_LOADER = 'CHANGE_LOADER';
export const CHANGE_OFFSET = 'CHANGE_OFFSET';
export const CHANGE_RESULTS_OFFSET = 'CHANGE_RESULTS_OFFSET';
export const GET_DRIVERS = 'GET_DRIVERS';
export const GET_RESULTS = 'GET_RESULTS';
export const REFRESH_DRIVERS = 'GET_DRIVERS';
export const REFRESH_RESULTS = 'GET_RESULTS';
